baseurl = "http://dev.owulveryck.info/gorchestrator/"
languageCode = "en-us"
title = "Gorchestrator"

# Theme to use (located in /themes/THEMENAME/)
theme = "bootie-docs"
copyright = "Copyright (c) 2016, Olivier Wulveryck; All rights reserved."


# example of config.toml
[params]
  description = "Gorchestrator: Orchestrator as a Service"
  repositoryUrl = "https://github.com/owulveryck/gorchestrator"
  mainMenu = ["about", "usage"]
